package banking.transfers.infrastructure.email;

import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class GestionDeCorreo {
	public static void enviarCorreo(MensajeEmail mensaje) {
		String emailDestino=mensaje.getEmailDeDestino();
		String tituloDelMensaje=mensaje.getTituloDeMensaje();
		String cuerpoDelMensaje = mensaje.getCuerpoDelMensaje();
		if(emailDestino==null)return;

        // Put sender’s address
        String from = "alan.garcia@imaginamedica.com";
        final String username = from;
        final String password = "01234567Ab";//password generated by Mailtrap

        // Paste host address from the SMTP settings tab in your Mailtrap Inbox
        String host = "smtp.yandex.com";

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.ssl.enable", "true");//it’s optional in Mailtrap  
        //props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap  
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "465");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

        // Get the Session object.
        Session session = Session.getInstance(props,
           new javax.mail.Authenticator() {
              protected PasswordAuthentication getPasswordAuthentication() {
                 return new PasswordAuthentication(username, password);
              }
           });

        try {
	      // Create a default MimeMessage object.
	      Message message = new MimeMessage(session);
	   
	      message.setHeader("Content-Type", "text/html;charset=UTF-8");
	      message.setHeader("Content-Transfer-Encoding", "quoted-printable");
	     
	      // Set From: header field 
	      message.setFrom(new InternetAddress(from));
	   
	      // Set To: header field
	      message.setRecipients(Message.RecipientType.TO,
	                 InternetAddress.parse(emailDestino));
	   
	      // Set Subject: header field
	      message.setSubject(tituloDelMensaje);
	   
	      // Put the content of your message
	      message.setContent(cuerpoDelMensaje,"text/html;charset=UTF-8");
	
	      // Send message
	      Transport.send(message);
	
	      //System.out.println("Sent message successfully....");

        } catch (MessagingException e) {
           throw new RuntimeException(e);
        }
     }
		
	
}
